### ISSUE TITLE
laravel 9 support

### ISSUE THREAD

**Issue by xetova-technology** [sicaboy/laravel-mfa#1]
tried installing this package on Laravel 9 and it seems it does support PHP 8.0
 
 composer require sicaboy/laravel-mfa
Info from https://repo.packagist.org: #StandWithUkraine
Cannot use sicaboy/laravel-mfa's latest version 1.2.1 as it requires php ~5.6|~7.0 which is not satisfied by your platform.

In PackageDiscoveryTrait.php line 317:

**Comment by sicaboy** [comment]
I will add support to new laravel and php asap

**Comment by sicaboy** [comment]
Version 1.2.2 published. Supports latest Laravel and php version.
